# -*- coding: utf-8 -*-
"""KuHalymie_Assignment2_DecisionMakingAndLoops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARPmurLmoYx6rOjgo1wncbONtx9d1jJy
"""

''' Exercise 1
Temperature Converter

write a python program to convert temperature in celsius and temperature in fahrenheit

[ Formula : c/5 = f-32/9 [where c = temperature in celsius and f = temperature in fahrenheit]]

expected output :

60 celcius is 140 in fahrenheit
45 in fahrenheit is 7 in celsius
'''
# Convert Celsius to Fahrenheit
celsius = float(input("Enter temperature in celsius: "))
fahrenheit = celsius * 9/5 + 32
print(f'Temperature in fahrenheit {fahrenheit:.2f}')      # :.2f --> It rounds the number and shows exactly 2 digits after the decimal.

# Convert Fahrenheit to Celsius
fahrenheit = float(input("Enter temperature in fahrenheit: "))
celsius = (fahrenheit - 32) / 1.8
print(f'Temperature in celsius {celsius:.2f}')            # :.2f --> It rounds the number and shows exactly 2 digits after the decimal.

# Temperature conversion program

print("1. Celsius to Fahrenheit")
print("2. Fahrenheit to Celsius")

choice = int(input("Select your choice (1 or 2): "))

if choice == 1:
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f'Temperature in fahrenheit {fahrenheit:.2f}')      # print(f"{celsius} °C = {fahrenheit:.2f} °F") --> option

elif choice == 2:
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print(f'Temperature in celsius {celsius:.2f}')            # print(f"{fahrenheit} °F = {celsius:.2f} °C") --> option

else:
    print("Invalid choice")

''' Excercise 2
Count Even and Odd Numbers

Write a Python program to count the number of even and odd numbers in a series of numbers

Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

Expected Output :

Number of even numbers : 4
Number of odd numbers : 5
'''
numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)    # tuple data type

count_odd = 0
count_even = 0

for x in numbers:
  if x % 2 == 0:
    count_even+=1
  else:
    count_odd+=1

print("Number of even numbers :",count_even)
print("Number of odd numbers :",count_odd)

# Counter Even & Odd

numbers = list(map(int, input("Enter multiple numbers by space: ").split()))

count_odd = 0
count_even = 0

for x in numbers:
  if x % 2 == 0:
    count_even+=1
  else:
    count_odd+=1

print("Number of even numbers :",count_even)
print("Number of odd numbers :",count_odd)

# Counter Even & Odd

user_input = input("Enter multiple numbers by space: ")
list_number = user_input.split()

numbers = []
for x in list_number:
    numbers.append(int(x))

count_odd = 0
count_even = 0

for x in numbers:
  if x % 2 == 0:
    count_even+=1
  else:
    count_odd+=1

print("Number of even numbers :",count_even)
print("Number of odd numbers :",count_odd)

''' Excercise 3
Fibonacci Series Between 0 and 50

Write a Python program to get the Fibonacci series between 0 and 50.

Note : The Fibonacci Sequence is the series of numbers :

0, 1, 1, 2, 3, 5, 8, 13, 21, ....
Every next number is found by adding up the two numbers before it.

Expected Output : 1 1 2 3 5 8 13 21 34
'''
x = 0
y = 1

while y < 50:
  print(y, end=' ')  # Print current Fibonacci number (y) on the same line
  x, y = y, x + y    # Update 'x' to previous 'y', 'y' to sum of previous 'x' + 'y'

# Fibonacci Sequence

x = 0
y = 1
user_input = int(input("Enter number: "))
while y < user_input:
  print(y, end=' ')  # Print current Fibonacci number (y) on the same line
  x, y = y, x + y    # Update 'x' to previous 'y', 'y' to sum of previous 'x' + 'y'

''' Excercise 4
FizzBuzz Variation

Write a Python program that iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of
the number and for multiples of five print "Buzz". For numbers that are multiples of three and five, print "FizzBuzz".

Sample Output :

1
2
fizz
4
buzz
'''
for num in range(1, 51):   # Loop through numbers from 1 to 50 using range function
    if num % 3 == 0 and num % 5 == 0:
        print("FizzBuzz")  # Print FizzBuzz for multiples of 3 and 5
    elif num % 3 == 0:
        print("Fizz")      # Print Fizz for multiples of 3
    elif num % 5 == 0:
        print("Buzz")      # Print Buzz for multiples of 5
    else:
        print(num)         # Print the number itself if not divisible by 3 or 5

# FizzBuzz Variation

result = []
n = int(input("Enter number: "))

for num in range(n+1):   # numbers from 0 to n using the range function
    if num % 15 == 0:
        result.append("FizzBuzz")
    elif num % 3 == 0:
        result.append("Fizz")
    elif num % 5 == 0:
        result.append("Buzz")
    else:
        result.append(str(num))

print("  ".join(result)) # "" to make separator between results & .join(result) combines all items in the list into one string

''' Excercise 5
Password Validity Checker

Write a Python program to check the validity of passwords input by users.

Validation :

At least 1 letter between [a-z] and 1 letter between [A-Z].
At least 1 number between [0-9].
At least 1 character from [$#@].
Minimum length 6 characters.
Maximum length 16 characters.
'''
# Link : https://www.w3schools.com/python/python_regex.asp
# Import the 're' module for regular expressions
import re   # Import regex module to check patterns in the password

# Prompt the user to input a password and store it in the variable 'p'
p = input("Input your password: ")

# Set 'x' to True to enter the while loop
x = True

# Start a while loop that continues until 'x' is True
while x:
    # Check conditions for a valid password:
    # Password length should be between 6 and 12 characters
    if (len(p) < 6 or len(p) > 12):
        break
    # Password should contain at least one lowercase letter
    elif not re.search("[a-z]", p):
        break
    # Password should contain at least one digit
    elif not re.search("[0-9]", p):
        break
    # Password should contain at least one uppercase letter
    elif not re.search("[A-Z]", p):
        break
    # Password should contain at least one special character among '$', '#', '@'
    elif not re.search("[$#@]", p):
        break
    # Password should not contain any whitespace character
    elif re.search("\\s", p):  # check is there any whitespace in the string
        break
    else:
        # If all conditions are met, print "Valid Password" and set 'x' to False to exit the loop
        print("Valid Password")
        x = False
        break

# If 'x' remains True, print "Not a Valid Password"
if x:
    print("Not a Valid Password")

# Password Validity Checker

import re  # Import regex module to check patterns in the password

# Ask user to input a password
password = input("Enter a password to check: ")

# Define regex patterns
lowercase = r"[a-z]"      # At least one lowercase letter
uppercase = r"[A-Z]"      # At least one uppercase letter
digit = r"[0-9]"           # At least one digit
special = r"[$#@]"         # At least one special character
length_valid = 6 <= len(password) <= 16  # Length between 6 and 16

# Check all conditions using regex
if (re.search(lowercase, password) and
    re.search(uppercase, password) and
    re.search(digit, password) and
    re.search(special, password) and
    length_valid):
    print("Password is valid")  # All conditions met
else:
    print("Password is invalid")  # Any condition missing

''' Excercise 6
Calculate the cube of all numbers from 1 to a given number.

Write a Python program to print the cube of all numbers from 1 to a given number

Given:

input_number = 6

Expected output:

Current Number is : 1  and the cube is 1
Current Number is : 2  and the cube is 8
Current Number is : 3  and the cube is 27
Current Number is : 4  and the cube is 64
Current Number is : 5  and the cube is 125
Current Number is : 6  and the cube is 216
'''
input_number = 6
for i in range(1, input_number + 1):
    print("Current Number is :", i, " and the cube is", (i * i * i))

# Cube of number calculation

input_number = int(input("Enter number: "))
for i in range(1, input_number + 1):
    print("Current Number is :", i, " and the cube is", (i * i * i))

"""**# SOLUTIONS **"""



''' Solution : Excercise 1

# Prompt the user to input a temperature in the format (e.g., 45F, 102C, etc.)
temp = input("Input the temperature you like to convert? (e.g., 45F, 102C etc.) : ")

# Extract the numerical part of the temperature and convert it to an integer
degree = int(temp[:-1])

# Extract the convention part of the temperature input (either 'C' or 'F')
i_convention = temp[-1]

# Check if the input convention is in uppercase 'C' (Celsius)
if i_convention.upper() == "C":
    # Convert the Celsius temperature to Fahrenheit
    result = int(round((9 * degree) / 5 + 32))
    o_convention = "Fahrenheit"  # Set the output convention as Fahrenheit
# Check if the input convention is in uppercase 'F' (Fahrenheit)
elif i_convention.upper() == "F":
    # Convert the Fahrenheit temperature to Celsius
    result = int(round((degree - 32) * 5 / 9))
    o_convention = "Celsius"  # Set the output convention as Celsius
else:
    # If the input convention is neither 'C' nor 'F', print an error message and exit the program
    print("Input proper convention.")
    quit()

# Display the converted temperature in the specified output convention
print("The temperature in", o_convention, "is", result, "degrees.")



'''

'''Solution : Excercise 2

# Create a tuple named 'numbers' containing integer values from 1 to 9
numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

# Initialize counters for counting odd and even numbers
count_odd = 0
count_even = 0

# Iterate through each element 'x' in the tuple 'numbers'
for x in numbers:
    # Check if the current number 'x' is even by evaluating 'not x % 2'
    if not x % 2:  # If 'x' modulo 2 equals 0, it's even
        # Increment the count of even numbers
        count_even += 1
    else:
        # If 'x' modulo 2 doesn't equal 0, it's odd; increment the count of odd numbers
        count_odd += 1

# Print the total count of even and odd numbers
print("Number of even numbers:", count_even)
print("Number of odd numbers:", count_odd)

'''

''' Solution : Excercise 3
# Initialize variables 'x' and 'y' with values 0 and 1, respectively
x, y = 0, 1

# Execute the while loop until the value of 'y' becomes greater than or equal to 50
while y < 50:
    # Print the current value of 'y'
    print(y)

    # Update the values of 'x' and 'y' using simultaneous assignment,
    # where 'x' becomes the previous value of 'y' and 'y' becomes the sum of 'x' and the previous value of 'y'
    x, y = y, x + y

'''

'''  Solution : Excercise 4


# Iterate through numbers from 0 to 50 using the range function
for fizzbuzz in range(51):
    # Check if the current number is divisible by both 3 and 5 (i.e., divisible by 15)
    if fizzbuzz % 3 == 0 and fizzbuzz % 5 == 0:
        # If divisible by both 3 and 5, print "fizzbuzz" and continue to the next iteration
        print("fizzbuzz")
        continue
    # Check if the current number is divisible only by 3
    elif fizzbuzz % 3 == 0:
        # If divisible only by 3, print "fizz" and continue to the next iteration
        print("fizz")
        continue
    # Check if the current number is divisible only by 5
    elif fizzbuzz % 5 == 0:
        # If divisible only by 5, print "buzz" and continue to the next iteration
        print("buzz")
        continue
    # If the number is neither divisible by 3 nor 5, print the number itself
    print(fizzbuzz)



'''

'''Solution : Excercise 5

Link : https://www.w3schools.com/python/python_regex.asp

# Import the 're' module for regular expressions
import re

# Prompt the user to input a password and store it in the variable 'p'
p = input("Input your password")

# Set 'x' to True to enter the while loop
x = True

# Start a while loop that continues until 'x' is True
while x:
    # Check conditions for a valid password:
    # Password length should be between 6 and 12 characters
    if (len(p) < 6 or len(p) > 12):
        break
    # Password should contain at least one lowercase letter
    elif not re.search("[a-z]", p):
        break
    # Password should contain at least one digit
    elif not re.search("[0-9]", p):
        break
    # Password should contain at least one uppercase letter
    elif not re.search("[A-Z]", p):
        break
    # Password should contain at least one special character among '$', '#', '@'
    elif not re.search("[$#@]", p):
        break
    # Password should not contain any whitespace character
    elif re.search("\s", p):
        break
    else:
        # If all conditions are met, print "Valid Password" and set 'x' to False to exit the loop
        print("Valid Password")
        x = False
        break

# If 'x' remains True, print "Not a Valid Password"
if x:
    print("Not a Valid Password")



'''

''' Solution : Excercise 6
input_number = 6
for i in range(1, input_number + 1):
    print("Current Number is :", i, " and the cube is", (i * i * i))

'''