# -*- coding: utf-8 -*-
"""KuHalymie_assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7AHJlRS3xu9HXDqs-emoFIBzCtuq0dG
"""

# Python String count() Method

# The count() method returns the number of times a specified value appears in the string.

txt = "I love apples, apple are my favorite fruit"
x = txt.count("apple")                              # Return the number of times the value "apple" appears in the string:
print(x)

txt = "I love apples, apple are my favorite fruit"
x = txt.count("apple", 15, 24)                      # Search from position 15 to 24:
print(x)

# Python String find() Method

# The find() method finds the first occurrence of the specified value.

# The find() method returns -1 if the value is not found.

# The find() method is almost the same as the index() method, the only difference is that the index() method raises an exception if the value is not found.

txt = "Hello, welcome to my world."
x = txt.find("e")                   # Where in the text is the first occurrence of the letter "e"?:
print(x)

txt = "Hello, welcome to my world."
x = txt.find("e", 5, 10)            # Where in the text is the first occurrence of the letter "e" when you only search between position 5 and 10?:
print(x)

txt = "Hello, welcome to my world."
x = txt.find("q")                   # If the value is not found, the find() method returns -1
print(x)

# Python String capitalize() Method

# The capitalize() method returns a string where the first character is upper case, and the rest is lower case.

txt = "hello, and welcome to my world."
x = txt.capitalize()
print (x)

txt = "python is FUN!"
x = txt.capitalize()                      # only first character uppercase, the rest will be lowercasse
print (x)

txt = "36 is my age."                     # number is not affected
x = txt.capitalize()
print (x)

# Python String casefold() Method

# The casefold() method returns a string where all the characters are lower case.

# This method is similar to the lower() method, but the casefold() method is stronger, more
# aggressive, meaning that it will convert more characters into lower case, and will find more
# matches when comparing two strings and both are converted using the casefold() method.

txt = "Hello, And Welcome To My World!"
x = txt.casefold()
print(x)

txt = "BANG BANG bang"                # change all words to lowercase
x = txt.casefold()
print(x)

# Python String lower() Method

# The lower() method returns a string where all characters are lower case.

# Symbols and Numbers are ignored.

txt = "Hello my FRIENDS"
x = txt.lower()           # it convert as whole, if need select certain word to be lowered need to apply slice....to be learned
print(x)

# Python String upper() Method

# The upper() method returns a string where all characters are in upper case.

# Symbols and Numbers are ignored.

txt = "Hello my friends"
x = txt.upper()           # it convert as whole, if need select certain word to be upper need to apply slice....to be learned
print(x)

# Python String swapcase() Method

# The swapcase() method returns a string where all the upper case letters are lower case and vice versa.

txt = "Hello My Name Is PETER"
x = txt.swapcase()
print(x)

# Python String islower() Method

# The islower() method returns True if all the characters are in lower case, otherwise False.

# Numbers, symbols and spaces are not checked, only alphabet characters.

txt = "hello world!"
x = txt.islower()       # Check if all the characters in the text are in lower case:
print(x)

a = "Hello world!"
b = "hello 123"         # number is considered lower case
c = "mynameisPeter"
print(a.islower())
print(b.islower())
print(c.islower())

# Python String isupper() Method

# The isupper() method returns True if all the characters are in upper case, otherwise False.

# Numbers, symbols and spaces are not checked, only alphabet characters.

txt = "THIS IS NOW!"        # Check if all the characters in the text are in upper case:
x = txt.isupper()
print(x)

a = "Hello World!"
b = "HELLO 123"             # number is considered upper case
c = "MY NAME IS PETER"
print(a.isupper())
print(b.isupper())
print(c.isupper())

# Python String replace() Method

# The replace() method replaces a specified phrase with another specified phrase.

txt = "I like bananas"
x = txt.replace("bananas", "apples")
print(x)

txt = "I like bananas"
x = txt.replace("bananas", "BANANAS 123")               # replace the word
print(x)

txt = "one one was a race horse, two two was one too."
x = txt.replace("one", "three")                         # Replace all occurrence of the word "one":
print(x)

txt = "one one was a race horse, two two was one too."
x = txt.replace("one", "three", 2)                      # Replace the two first occurrence of the word "one":
print(x)

# Python String startswith() Method

# The startswith() method returns True if the string starts with the specified value, otherwise False.

txt = "Hello, welcome to my world."
x = txt.startswith("Hello")
print(x)

txt = "Hello, welcome to my world."
x = txt.startswith("wel", 7, 20)          # Check if position 7 to 20 starts with the characters "wel":
print(x)

txt = "Hello, welcome to my world."
x = txt.startswith("Hello", 7, 20)          # Check if position 7 to 20 starts with the characters "Hello:
print(x)

txt = "Hi, welcome to my world."
x = txt.startswith(("Hello", "Hi"))       # Check if the string starts with either "Hello" or "Hi":
print(x)

# Python String endswith() Method

# The endswith() method returns True if the string ends with the specified value, otherwise False.

txt = "Hello, welcome to my world."
x = txt.endswith(".")
print(x)

txt = "Hello, welcome to my world."
x = txt.endswith("my world.")               # Check if the string ends with the phrase "my world.":
print(x)

txt = "Hello, welcome to my world."
x = txt.endswith("my world.", 5, 11)        # Check if position 5 to 11 ends with the phrase "my world.":
print(x)

txt = "Hello, welcome to my world."
x = txt.endswith("my world.", 18, 28)       # Check if position 18 to 28 ends with the phrase "my world.":
print(x)

txt = "Hello, welcome to my castle."
x = txt.endswith(("world.", "castle."))     # Check if the string ends with either the phrase "world." or "castle.":
print(x)