# -*- coding: utf-8 -*-
"""KuHalymie_Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMQQtgh3PuivOrQ5jmZqoJfZKsNi9iNQ
"""

# Assignment 3
# Data Structures And Functions

# Q1. Python program to count positive and negative numbers in a list.

a = [10, -20, 30, -40, 50, -60, 0]
pos = 0      # to count +ve number here
neg = 0      # to count -ve number here
for n in a:
    if n > 0:
        pos += 1
    elif n < 0:
        neg += 1
print("Positive numbers:", pos)
print("Negative numbers:", neg)

# Q2. Using list comprehension. Write a python program to count positive and negative numbers in a list.

a = [10, -20, 30, -40, 50, -60, 0]
pos = len([n for n in a if n > 0])
neg = len([n for n in a if n < 0])

print("Positive numbers:", pos)
print("Negative numbers:", neg)

# Q3. Remove multiple elements from list in python.

# Using For Loop
a = [10, 20, 30, 40, 50, 60, 70]   # remove 20, 40, 60
res = []
for val in a:
  if val not in (20, 40, 60):                        # or can set remove=[20,40,60] as variable
    res.append(val)
print(res)

# Using List Comprehension
a = [10, 20, 30, 40, 50, 60, 70]   # remove 20, 40, 60
res = [val for val in a if val not in (20, 40, 60)]   # or can set remove=[20,40,60] as variable
print(res)

# Q4. Remove duplicates from list in Python

# Using For Loop ver.1
a = [1, 2, 2, 3, 4, 4, 5]
for n in a:
    if a.count(n) > 1:
        a.remove(n)
print(a)

# Using For Loop ver.2
a = [1, 2, 2, 3, 4, 4, 5]
res = []
for val in a:  # Iterate through each value in the list 'a'
     if val not in res:   # Check if the value is not already in 'res'
        res.append(val)   # If not present, append it to 'res'
print(res)

# Using List Comprehension
a = [1, 2, 2, 3, 4, 4, 5]
res = []
[res.append(x) for x in a if x not in res]
print(res)

# Using Set ()
a = [1, 2, 2, 3, 4, 4, 5]
res = list(set(a))
print(res)

# Q5. Python program to find the sum of all items in a dictionary
# Input : {'a':100, 'b':200, 'c':300}
# Output : 600

# Using  for loop
d = {'a':100, 'b':200, 'c':300}
res = 0
for value in d.values():
  res += value            # res = res + value
print (res)

# Using sum
d = {'a':100, 'b':200, 'c':300}
res = 0
print(sum(d.values()))

# Q6. Key in Maximum Unique Values - Python
# dict1 = {"key1":[5,7,5,4,5], "key2":[6,7,4,3,3], "key3":[9,9,6,5,5]}
# Output : key2

dict1 = {"key1":[5,7,5,4,5], "key2":[6,7,4,3,3], "key3":[9,9,6,5,5]}
max_key, max_val = None, 0

for k,v in dict1.items():
  unique_count = len(set(v))
  if unique_count > max_val:
    max_val, max_key = unique_count, k
print(max_key)

# Q7. Story: An online store records daily product sales.
# Convert this list into total sales per product.
sales = [
    ("apple", 3),
    ("banana", 2),
    ("apple", 5),
    ("banana", 1),
    ("orange", 4)
]

# Output : {'apple': 8, 'banana': 3, 'orange': 4}

total_sales = {}

for product, qty in sales:
    total_sales[product] = total_sales.get(product, 0) + qty  # If product exists → return its current total, if not → return 0

print(total_sales)

# Q8. Undo Feature in Text Editor
# A text editor supports an undo operation.
# Given operations:
# actions = ["type A", "type B", "delete", "type C"]
# Output : ['type A', 'type C']

# actions = ["type A", "type B", "delete", "type C","type B","delete","type A","type C","delete"]
# Output : ['type A', 'type C', 'type A']

actions = ["type A", "type B", "delete", "type C","type B","delete","type A","type C","delete"]
stack = []

for action in actions:
    if action == "delete" and stack:  # only delete if the action is "delete" and stack is not empty. to prevent crash at line 15.
        stack.pop()  # remove last item from stack.
    else:
        stack.append(action)   # add action in stack

print(stack)

# Q9. Print the index number of those Two boxes whose weights sum to a target.
# weights = [2, 7, 11, 15 , 6 , 3, 7 , 3 , 7 , 2]
# target = 9

weights = [2, 7, 11, 15 , 6 , 3, 7 , 3 , 7 , 2]
target = 9
seen = {}

for i, w in enumerate(weights):   # loop with index (i) + value (w)
    if target - w in seen:
        print(seen[target - w], i)
    seen[w] = i

# Q10. Online Store Price Update (map + lambda)
# An online store increases all product prices by 10%.
# prices = [100, 200, 300, 400]
# output [110, 220, 330, 440]

# using map+lambda
prices = [100, 200, 300, 400]
new_prices = list(map(lambda x: int(x * 1.10), prices))
# map() is used to apply a function to every item in an iterable (like a list)
# map(function, iterable)
# lambda is a small anonymous function
# lambda arguments: expression
print(new_prices)


# using for
prices = [100, 200, 300, 400]
new_prices2 = []
for x in prices:
    new_prices2.append(int(x * 1.10))   # can replace int with round
print(new_prices2)

# Q11. Employee Bonus System (map + if–else)
# Employees earning ≥ 50,000 get a 20% bonus, others get 10%.

# using map + if-else
salaries = [40000, 60000, 50000, 30000]
bonus = list(map(lambda s: round(s * 1.2) if s >= 50000 else round(s * 1.1), salaries))
print(bonus)


# using if-else
salaries = [40000, 60000, 50000, 30000]
bonus = []

for s in salaries:
    if s >= 50000:
        # 20% bonus
        bonus.append(round(s * 1.20))
    else:
        # 10% bonus
        bonus.append(round(s * 1.10))
print(bonus)

# Q12. Order Filtering System (filter + multiple conditions)
# An e-commerce system wants orders above 1000 and status not cancelled.

orders = [
    {"amount": 1200, "status": "completed"},
    {"amount": 800, "status": "completed"},
    {"amount": 1500, "status": "cancelled"},
    {"amount": 2000, "status": "completed"}
]
# using filter + multiple conditions
valid_orders = list(filter(
    lambda o: o["amount"] > 1000 and o["status"] == "completed",orders))
# filter() is used to select only items from a list (or any iterable) that satisfy a condition.
# filter(function, iterable)
print(valid_orders)

# using for loop
valid_orders = []
for oo in orders:
    if oo["amount"] > 1000 and oo["status"] == "completed":
        valid_orders.append(oo)
print(valid_orders)

# Q13. Data Cleaning Pipeline (map + filter + lambda)
# From a data pipeline:
#  a.)Remove negative numbers
#  b.) Square remaining numbers
#  c.) Keep only results > 50

# data = [-4, -1, 2, 4, 8]
# Output : [64]

data = [-4, -1, 2, 4, 8]

# using map + filter + lambda
cleaned = list(filter(lambda x: x > 50,map(lambda x: x**2, filter(lambda x: x >= 0, data))))
print(cleaned)

# Breakdown
# Step 1: remove negatives
positive_data = filter(lambda x: x >= 0, data) # Keeps only numbers 0 or greater → [2, 4, 8]
# Step 2: square numbers
squared_data = map(lambda x: x**2, positive_data) # Squares each number → [4, 16, 64]
# Step 3: keep numbers > 50 → [64]
final_data = list(filter(lambda x: x > 50, squared_data)) # list() → converts filter object to list so we can print
print(final_data)

# using for loop
result = []
for x in data:
    if x >= 0:            # Step a: remove negatives
        squared = x**2    # Step b: square
        if squared > 50:  # Step c: keep > 50
            result.append(squared)
print(result)

# Using list comprehension
result = [x**2 for x in data if x >= 0 and x**2 > 50]
print(result)